<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>widdo</artifactId>
        <groupId>cn.widdo</groupId>
        <version>353.0.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>widdo-register</artifactId>
    <packaging>jar</packaging>
    <name>widdo-register</name>
    <description>nacos 注册配置中心</description>

    <!--    <properties>
            <maven.compiler.source>17</maven.compiler.source>
            <maven.compiler.target>17</maven.compiler.target>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        </properties>-->

    <dependencies>
        <dependency>
            <groupId>cn.widdo</groupId>
            <artifactId>widdo-assistant</artifactId>
        </dependency>
    </dependencies>

</project>