<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>widdo-bom</artifactId>
    <groupId>cn.widdo</groupId>
    <version>353.0.0.0</version>
    <packaging>pom</packaging>

    <name>widdo-bom</name>
    <description>widdo bom</description>

    <properties>

        <spring-boot-dependencies.version>3.5.3</spring-boot-dependencies.version>
        <spring-cloud-dependencies.version>2025.0.0</spring-cloud-dependencies.version>
        <spring-cloud-alibaba-dependencies.version>2022.0.0.0</spring-cloud-alibaba-dependencies.version>
        <!--        <spring-cloud-stream-dependencies.version>3.2.2</spring-cloud-stream-dependencies.version>-->
        <spring-framework-bom.version>6.2.8</spring-framework-bom.version>
        <spring-security-bom.version>6.5.1</spring-security-bom.version>


        <!--Maven Plugin 相关组件-->
        <dockerfile-maven-plugin.version>1.4.13</dockerfile-maven-plugin.version>
        <docker-maven-plugin.version>0.39.0</docker-maven-plugin.version>
        <git-commit-id-plugin.version>4.9.9</git-commit-id-plugin.version>
        <mapstruct-processor.version>1.4.2.Final</mapstruct-processor.version>
        <maven-archetype-plugin.version>3.2.1</maven-archetype-plugin.version>
        <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
        <maven-resources-plugin.version>3.2.0</maven-resources-plugin.version>
        <maven-surefire-plugin.version>2.22.2</maven-surefire-plugin.version>
        <maven-source-plugin.version>3.2.1</maven-source-plugin.version>
        <versions-maven-plugin.version>2.8.1</versions-maven-plugin.version>
        <git-commit-id-plugin.version>4.9.10</git-commit-id-plugin.version>
        <maven-checkstyle-plugin.version>3.2.0</maven-checkstyle-plugin.version>

        <!--通用开源工具依赖包-->
        <commons-lang3.version>3.12.0</commons-lang3.version>
        <google-guava.version>31.0.1-jre</google-guava.version>

        <!--辅助工具依赖包-->
        <!---->
        <lombok.version>1.18.36</lombok.version>
        <p6spy.version>3.9.1</p6spy.version>

        <!--阿里巴巴开源工具-->
        <fastjson.version>1.2.83</fastjson.version>

        <!--国内开源工具依赖包-->
        <hutool.verion>5.8.12</hutool.verion>

        <!--第三方工具依赖包-->
        <!--缓存依赖包-->
        <redisson.version>3.15.3</redisson.version>
        <mybatis-plus-boot-starter.version>3.5.2</mybatis-plus-boot-starter.version>
        <mybatis-plus-generator.version>3.5.2</mybatis-plus-generator.version>
        <assertj.version>3.22.0</assertj.version>

        <!--切面-->
        <aspectj.version>1.9.19</aspectj.version>

        <!--图数据库相关工具依赖包-->
        <neo4j-java-driver.version>5.28.9</neo4j-java-driver.version>
        <neo4j.version>5.26.5</neo4j.version>
        <!--start @since 302.1.0.0-->
        <neo4j-spark.version>4.1.5_for_spark_3</neo4j-spark.version>
        <!--        <neo4j-spark.version>4.1.1_for_spark_2.4</neo4j-spark.version>-->
        <!--end-->

        <orientdb-jdbc.version>3.0.29</orientdb-jdbc.version>
        <orientdb-gremlin.version>3.0.29</orientdb-gremlin.version>

        <!--系统信息-->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>21</java.version>
        <resource.delimiter>@</resource.delimiter>

        <!--wordnet相关-->
        <jwi.version>2.1.3</jwi.version>

        <!--spark相关 @since 302.1.0.0-->
        <!--        <spark.version>2.4.8</spark.version>-->
        <spark.version>3.1.3</spark.version>
        <scala.version>2.12</scala.version>
        <janino.version>3.0.8</janino.version>
        <!--end -->

        <!--jena相关-->
        <jena-lib.version>4.9.0</jena-lib.version>

        <!--grpc-->
        <grpc.version>1.53.0</grpc.version>

        <!--漏洞升级-->
        <commons-text.version>1.10.0</commons-text.version>
        <protobuf-java.version>3.21.7</protobuf-java.version>
        <ivy.version>2.5.1</ivy.version>
        <gremlin-core.version>3.5.2</gremlin-core.version>
        <commons-configuration2.version>2.8.0</commons-configuration2.version>
        <jettison.version>1.5.4</jettison.version>
        <org.codehaus.groovy.version>3.0.9</org.codehaus.groovy.version>
        <snakeyaml.version>2.0</snakeyaml.version>

        <!--自然语言处理-->
        <hanlp.version>portable-1.8.4</hanlp.version>

        <!--hadoop-->
        <hadoop-client.version>3.1.3</hadoop-client.version>

        <!--mockite单元测试-->
        <mockito.version>4.8.1</mockito.version>
        <powermock.version>2.0.9</powermock.version>

        <!--druid-->
        <druid.version>1.2.18</druid.version>

        <!--dubbo-->
        <dubbo.version>3.2.4</dubbo.version>

        <!--elasticsearch-->
        <elasticsearch.version>7.17.14</elasticsearch.version>

        <!--配置参数-->
        <!--为了便于Docker的构建，减少上下文影响，将所有Docker资源放置在同一个目录中进行构建-->
        <!--docker信息改为自己的-->
        <docker.build.directory>../../configurations/docker/context/target</docker.build.directory>
        <docker.resource.name>${project.build.finalName}.${project.packaging}</docker.resource.name>
        <docker.host>http://101.42.10.77:2375</docker.host>
        <docker.namespace>101.42.10.77:5000</docker.namespace>
        <!--        <docker.registry>https://hub.docker.com</docker.registry>-->
        <docker.registry>101.42.10.77:5000</docker.registry>
        <docker.username>widdo</docker.username>
        <docker.password>widdo_docker</docker.password>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- 升级，替换为 com.alibaba.cloud -->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!--dubbo-->
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-bom</artifactId>
                <version>${dubbo.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-bom</artifactId>
                <version>${spring-security-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-framework-bom</artifactId>
                <version>${spring-framework-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--widdo依赖-->
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>widdo-assistant</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>widdo-cache</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>widdo-data</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>widdo-autoconfigure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>widdo-starter-neo4j</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>widdo-starter-orientdb</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.widdo</groupId>
                <artifactId>widdo-starter-jena</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.widdo</groupId>
                <artifactId>widdo-hadoop</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.widdo</groupId>
                <artifactId>widdo-starter-hadoop</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.widdo</groupId>
                <artifactId>widdo-starter-sql</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.widdo</groupId>
                <artifactId>widdo-starter-elasticsearch</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!--通用开源工具-->
            <!--            <dependency>
                            <groupId>org.apache.commons</groupId>
                            <artifactId>commons-lang3</artifactId>
                            <version>${commons-lang3.version}</version>
                        </dependency>-->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${google-guava.version}</version>
                <scope>compile</scope>
            </dependency>

            <!--辅助工具-->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>p6spy</groupId>
                <artifactId>p6spy</artifactId>
                <version>${p6spy.version}</version>
            </dependency>


            <!--阿里巴巴开源工具-->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>${fastjson.version}</version>
            </dependency>

            <!--国内开源工具-->
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.verion}</version>
            </dependency>

            <!--第三方工具-->
            <!-- redisson 分布式锁-->
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson.version}</version>
            </dependency>

            <!--存在SQL注入漏洞。漏洞场景：like；in；order by。需要预编译-->
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>${mybatis-plus-boot-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>${mybatis-plus-generator.version}</version>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${assertj.version}</version>
                <scope>test</scope>
            </dependency>

            <!--切面-->
            <dependency>
                <groupId>org.aspectj</groupId>
                <artifactId>aspectjrt</artifactId>
                <version>${aspectj.version}</version>
            </dependency>

            <dependency>
                <groupId>org.aspectj</groupId>
                <artifactId>aspectjweaver</artifactId>
                <version>${aspectj.version}</version>
            </dependency>

            <!--图数据库工具-->
            <!--neo4j-->
            <dependency>
                <groupId>org.neo4j.driver</groupId>
                <artifactId>neo4j-java-driver</artifactId>
                <version>${neo4j-java-driver.version}</version>
            </dependency>
            <!--Add a dependency section that includes the procedure and function APIs, which procedures and functions use at runtime.-->
            <dependency>
                <groupId>org.neo4j</groupId>
                <artifactId>neo4j</artifactId>
                <version>${neo4j.version}</version>
                <scope>provided</scope>
                <exclusions>
                    <!--解决漏洞：排除1.5.2，升级为1.5.4-->
                    <exclusion>
                        <groupId>org.codehaus.jettison</groupId>
                        <artifactId>jettison</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!--Add dependencies that are necessary for testing the procedure.-->
            <dependency>
                <groupId>org.neo4j.test</groupId>
                <artifactId>neo4j-harness</artifactId>
                <version>${neo4j.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.orientechnologies</groupId>
                <artifactId>orientdb-jdbc</artifactId>
                <version>${orientdb-jdbc.version}</version>
            </dependency>
            <dependency>
                <groupId>com.orientechnologies</groupId>
                <artifactId>orientdb-gremlin</artifactId>
                <version>${orientdb-gremlin.version}</version>
                <exclusions>
                    <!--解决漏洞：排除3.3.0依赖，升级为3.5.2-->
                    <exclusion>
                        <groupId>org.apache.tinkerpop</groupId>
                        <artifactId>gremlin-core</artifactId>
                    </exclusion>

                    <!--解决漏洞：排除2.4.11，升级为3.0.9-->
                    <exclusion>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.neo4j</groupId>
                <artifactId>neo4j-connector-apache-spark_2.12</artifactId>
                <version>${neo4j-spark.version}</version>
            </dependency>

            <!--wordnet相关-->
            <dependency>
                <groupId>edu.mit.jwi</groupId>
                <artifactId>edu.mit.jwi</artifactId>
                <version>${jwi.version}</version>
            </dependency>

            <!--spark相关 @since 302.1.0.0-->
            <dependency>
                <groupId>org.apache.spark</groupId>
                <artifactId>spark-core_2.12</artifactId>
                <version>${spark.version}</version>
                <!--排除log4j12,解决和logback冲突问题-->
                <exclusions>
                    <exclusion>
                        <artifactId>slf4j-log4j12</artifactId>
                        <groupId>org.slf4j</groupId>
                    </exclusion>
                    <!--解决漏洞问题：排除spark-core中的1.9 commons-text，升级为1.10.0-->
                    <exclusion>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-text</artifactId>
                    </exclusion>

                    <!--解决漏洞：排除2.5.0，升级为2.5.1-->
                    <exclusion>
                        <groupId>org.apache.ivy</groupId>
                        <artifactId>ivy</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.spark</groupId>
                <artifactId>spark-sql_2.12</artifactId>
                <version>${spark.version}</version>
                <!--解决漏洞：排除2.5.0，升级为3.21.7-->
                <exclusions>
                    <exclusion>
                        <groupId>com.google.protobuf</groupId>
                        <artifactId>protobuf-java</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <dependency>
                <groupId>org.codehaus.janino</groupId>
                <artifactId>janino</artifactId>
                <version>${janino.version}</version>
            </dependency>
            <!--end-->

            <!--jena-->
            <dependency>
                <groupId>org.apache.jena</groupId>
                <artifactId>apache-jena-libs</artifactId>
                <type>pom</type>
                <version>${jena-lib.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.jena</groupId>
                <artifactId>jena</artifactId>
                <version>${jena-lib.version}</version>
                <type>pom</type>
            </dependency>

            <dependency>
                <groupId>org.apache.jena</groupId>
                <artifactId>jena-core</artifactId>
                <version>${jena-lib.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.jena</groupId>
                <artifactId>jena-base</artifactId>
                <version>${jena-lib.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>org.apache.jena</groupId>
                <artifactId>jena-iri</artifactId>
                <version>${jena-lib.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.jena</groupId>
                <artifactId>jena-arq</artifactId>
                <version>${jena-lib.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.jena</groupId>
                <artifactId>jena-rdfconnection</artifactId>
                <version>${jena-lib.version}</version>
            </dependency>

            <!--grapc-->
            <dependency>
                <groupId>io.grpc</groupId>
                <artifactId>grpc-all</artifactId>
                <version>${grpc.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-validation</artifactId>
                <version>${spring-boot-dependencies.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.yaml</groupId>
                        <artifactId>snakeyaml</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!--漏洞升级-->
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-text</artifactId>
                <version>${commons-text.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>com.google.protobuf</groupId>
                <artifactId>protobuf-java</artifactId>
                <version>${protobuf-java.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.ivy</groupId>
                <artifactId>ivy</artifactId>
                <version>${ivy.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.tinkerpop</groupId>
                <artifactId>gremlin-core</artifactId>
                <version>${gremlin-core.version}</version>
                <exclusions>
                    <!--解决漏洞：排除2.7，升级为2.8-->
                    <exclusion>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-configuration2</artifactId>
                    </exclusion>
                    <!--解决漏洞：排除1.33，升级为2.0-->
                    <exclusion>
                        <groupId>org.yaml</groupId>
                        <artifactId>snakeyaml</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-configuration2</artifactId>
                <version>${commons-configuration2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codehaus.jettison</groupId>
                <artifactId>jettison</artifactId>
                <version>${jettison.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codehaus.groovy</groupId>
                <artifactId>groovy</artifactId>
                <version>${org.codehaus.groovy.version}</version>
            </dependency>
            <dependency>
                <groupId>org.yaml</groupId>
                <artifactId>snakeyaml</artifactId>
                <version>${snakeyaml.version}</version>
            </dependency>

            <dependency>
                <groupId>com.hankcs</groupId>
                <artifactId>hanlp</artifactId>
                <version>${hanlp.version}</version>
            </dependency>

            <!--hadoop相关 start-->
            <dependency>
                <groupId>org.apache.hadoop</groupId>
                <artifactId>hadoop-client</artifactId>
                <version>${hadoop-client.version}</version>
            </dependency>

            <!--mockito单元测试-->
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
            </dependency>
            <!--powermock.对mockito的增强，弥补mockito缺失的静态方法mock-->
            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-module-junit4</artifactId>
                <version>${powermock.version}</version>
                <!--                <scope>test</scope>-->
            </dependency>

            <dependency>
                <groupId>org.powermock</groupId>
                <artifactId>powermock-api-mockito2</artifactId>
                <version>${powermock.version}</version>
                <!--                <scope>test</scope>-->
            </dependency>

            <!--druid-->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid</artifactId>
                <version>${druid.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-starter</artifactId>
                <version>${dubbo.version}</version>
            </dependency>


            <!--elasticsearch-->
            <dependency>
                <groupId>org.elasticsearch</groupId>
                <artifactId>elasticsearch</artifactId>
                <version>${elasticsearch.version}</version>
            </dependency>

            <dependency>
                <groupId>org.elasticsearch.client</groupId>
                <artifactId>elasticsearch-rest-high-level-client</artifactId>
                <version>${elasticsearch.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!--<distributionManagement>
        <repository>
            &lt;!&ndash;id的名字可以任意取，但是在setting文件中的属性<server>的ID与这里一致&ndash;&gt;
            <id>releases</id>
            &lt;!&ndash;指向仓库类型为host(宿主仓库）的储存类型为Release的仓库&ndash;&gt;
            <url>http://localhost:8081/repository/semanticcube-release/</url>
        </repository>
        <snapshotRepository>
            <id>snapshots</id>
            &lt;!&ndash;指向仓库类型为host(宿主仓库）的储存类型为Snapshot的仓库&ndash;&gt;
            <url>http://localhost:8081/repository/semanticcube-snapshot/</url>
        </snapshotRepository>
    </distributionManagement>-->
</project>