<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>widdo-services</artifactId>
        <groupId>cn.widdo</groupId>
        <version>353.0.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>widdo-study</artifactId>
    <version>353.0.0.0</version>

    <name>widdo-study</name>
    <description>widdo-study</description>

    <dependencies>
        <!--自动配置包-->
        <dependency>
            <groupId>cn.widdo</groupId>
            <artifactId>widdo-autoconfigure</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.widdo</groupId>
            <artifactId>widdo-cache</artifactId>
        </dependency>

        <!--neo4j starter-->
        <dependency>
            <groupId>cn.widdo</groupId>
            <artifactId>widdo-starter-neo4j</artifactId>
        </dependency>

        <!--orientdb starter-->
        <dependency>
            <groupId>cn.widdo</groupId>
            <artifactId>widdo-starter-orientdb</artifactId>
        </dependency>

        <!--@since 302.1.0.0-->
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino</artifactId>
        </dependency>

        <!--grpc-->
        <dependency>
            <groupId>io.grpc</groupId>
            <artifactId>grpc-all</artifactId>
        </dependency>

        <!--解决漏洞：升级的组件，具体参考widdo-dependencies-->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.ivy</groupId>
            <artifactId>ivy</artifactId>
        </dependency>

        <dependency>
            <groupId>com.hankcs</groupId>
            <artifactId>hanlp</artifactId>
        </dependency>

        <!--druid-->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.widdo</groupId>
            <artifactId>widdo-starter-sql</artifactId>
        </dependency>

        <dependency>
            <groupId>cn.widdo</groupId>
            <artifactId>widdo-starter-elasticsearch</artifactId>
        </dependency>
    </dependencies>
    <build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.6.1</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                        <exclude>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-devtools</artifactId>
                        </exclude>
                    </excludes>

                    <!--<image>
                        <env>
                            &lt;!&ndash; 安全加固 &ndash;&gt;
                            <BP_OCI_USER_ID>1000</BP_OCI_USER_ID>
                            <BP_OCI_USER_NAME>appuser</BP_OCI_USER_NAME>

                            &lt;!&ndash; JVM 优化 &ndash;&gt;
                            <BPE_DELIM_JAVA_TOOL_OPTIONS xml:space="preserve"> </BPE_DELIM_JAVA_TOOL_OPTIONS>
                            <BPE_APPEND_JAVA_TOOL_OPTIONS>-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0</BPE_APPEND_JAVA_TOOL_OPTIONS>

                            &lt;!&ndash; 生产配置 &ndash;&gt;
                            <BPL_SPRING_CLOUD_BINDINGS_ENABLED>false</BPL_SPRING_CLOUD_BINDINGS_ENABLED>
                        </env>
                    </image>-->
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
            </plugin>

            <!--proto-->
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.6.1</version>
                <configuration>
                    <protocArtifact>com.google.protobuf:protoc:3.5.1-1:exe:${os.detected.classifier}</protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.16.1:exe:${os.detected.classifier}</pluginArtifact>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>