spring:
  cloud:
    gateway:
      discovery:
        locator:
          #Flag that enables DiscoveryClient gateway integration
          enabled: true
      enabled: true
    nacos:
      discovery:
        server-addr: 101.42.10.77:8848
        namespace: widdo-env
        group: DEFAULT_GROUP
        register-enabled: true
      config:
        server-addr: 101.42.10.77:8848
        namespace: widdo-env
        group: DEFAULT_GROUP
        enabled: true
      username: nacos
      password: widdo_nacos
  config:
    activate:
      on-profile: env
    import:
      - optional:nacos:widdo-environment.yaml
      - optional:nacos:widdo-gateway.yaml