server:
  port: ${STUDY_PORT:9902}
spring:
  application:
    name: @project.artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:widdo-register}:${NACOS_PORT:8846}
        namespace: @nacos.namespace@
        group: @nacos.group@
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: @nacos.namespace@
        group: @nacos.group@
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
  config:
    import:
      - optional:nacos:@yaml.prefix@-@yaml.suffix@.yaml
      - optional:nacos:@yaml.prefix.default@-@profiles.active@.yaml
      - optional:nacos:${spring.application.name}-@profiles.active@.yaml

#banner中打印的模板信息
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"


management:
  endpoint:
    threaddump:
      enabled: true